server:
  port: 8081

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/Gongzhonghao?useUnicode=true & characterEncoding=utf-8 &
      useSSL=true & serverTimezone=Asia/Shanghai
    username: root
    password: quxiaochen2010

mybatis-plus:
  mapper-locations: classpath:/mybatis_mapper/**/*Mapper.xml
#  type-aliases-package: com.example.gongzhonghao.Domain